name: Test, build and publish application to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  DOCKER_URL: hub.docker.com/repository/docker/averagewizard13/sockbot-discord

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn dependencies
        run: yarn install

      - name: Check ESLint
        run: yarn lint

      - name: Check Prettier formatting
        run: yarn fmt:check

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # For tags to be fetched
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: averagewizard13/sockbot-discord
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy Docker image
    if: ${{ false }} # disable for now
    runs-on: ubuntu-latest
    needs:
      - test
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
